PRESET_BASE: mainnet
CONFIG_NAME: interop
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 8
GENESIS_DELAY: 0
SECONDS_PER_SLOT: 2
SLOTS_PER_EPOCH: 8
TERMINAL_TOTAL_DIFFICULTY: 0
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
ETH1_FOLLOW_DISTANCE: 0
SECONDS_PER_ETH1_BLOCK: 14
GENESIS_FORK_VERSION: 0x20000089
ALTAIR_FORK_VERSION: 0x20000090
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x20000093
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_VERSION: 0x20000094
ELECTRA_FORK_EPOCH: 0
FULU_FORK_VERSION: 0x20000095
FULU_FORK_EPOCH: 18446744073709551615
